var races = [
    {
        "name":"Human",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "desc": "Puny widdle normal hooman",
        "str": 0,
        "dex": 0,
        "con": 0,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "benefits": "Class flexibility",
        "lang": "Common"
    },
    {
        "name":"Elf",
        "height_ft": 6,
        "height_in": 5,
        "weight": 140,
        "desc": "tall gangly guys",
        "str": 0,
        "dex": 1,
        "con": -1,
        "int": 0,
        "wis": 1,
        "cha": 0,
        "benefits": "Darkvision: See up to 60ft in darkness",
        "lang": "Common, Elvish"
    },
    {
        "name":"Half-Elf",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "desc": "Puny widdle normal hooman",
        "str": 0,
        "dex": 0,
        "con": 0,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "benefits": "Class flexibility",
        "lang": "Common"
    },
    {
        "name":"Dwarf",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "desc": "Puny widdle normal hooman",
        "str": 0,
        "dex": 0,
        "con": 0,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "benefits": "Class flexibility",
        "lang": "Common"
    },
    {
        "name":"Gnome",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "desc": "Puny widdle normal hooman",
        "str": 0,
        "dex": 0,
        "con": 0,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "benefits": "Class flexibility",
        "lang": "Common"
    },
    {
        "name":"Halfling",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "desc": "Puny widdle normal hooman",
        "str": 0,
        "dex": 0,
        "con": 0,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "benefits": "Class flexibility",
        "lang": "Common"
    },
    {
        "name":"Orc",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "desc": "Puny widdle normal hooman",
        "str": 0,
        "dex": 0,
        "con": 0,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "benefits": "Class flexibility",
        "lang": "Common"
    },
    {
        "name":"Half-Orc",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "desc": "Puny widdle normal hooman",
        "str": 0,
        "dex": 0,
        "con": 0,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "benefits": "Class flexibility",
        "lang": "Common"
    }
];