var races = [
    {
        "name":"Human",
        "height_ft": 5,
        "height_in": 10,
        "weight": 190,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Humans are the most adaptable of the races, able to survive comfortably in many environments and situations. Because of this, their civilizations span across the world, diverse cultures sprawling across all the land. They are curious, ambitious, and adventurous, traits which match as well with a traveling bard as they do with a conquering emperor.",
        "traits": "Bonus Feat, Skilled",
        "lang": "Common",
        "link": "http://phaser.io/examples/v2/category/tilemaps"
    },
    {
        "name":"Elf",
        "height_ft": 6,
        "height_in": 5,
        "weight": 140,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "tall gangly guys",
        "traits": "Darkvision: See up to 60ft in darkness",
        "lang": "Common, Elvish",
        "link": ""
    },
    {
        "name":"Half-Elf",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Puny widdle normal hooman",
        "traits": "Class flexibility",
        "lang": "Common",
        "link": ""
    },
    {
        "name":"Dwarf",
        "height_ft": 4,
        "height_in": 0,
        "weight": 260,
        "mods": "+2 Con | +2 Wis | -2 Cha",
        "spd": 20,
        "size": "Medium",
        "desc": "Dwarves are short, stocky, hairy, powerful beings known for their affinity for mining and craftsmanship. They're formidable fighters who prefer living in high mountain cities and deep caverns, carving their buildings from the rock itself. Dwarves are steadfast, stubborn, and conservative creatures, loyal to the end.",
        "traits": "Darkvision, Defensive Training, Greed, Hatred, Hardy, Stability, Stonecunning, Weapon Familiarity",
        "lang": "Common, Dwarven",
        "link": ""
    },
    {
        "name":"Gnome",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Puny widdle normal hooman",
        "traits": "Class flexibility",
        "lang": "Common",
        "link": ""
    },
    {
        "name":"Halfling",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Puny widdle normal hooman",
        "traits": "Class flexibility",
        "lang": "Common",
        "link": ""
    },
    {
        "name":"Orc",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Puny widdle normal hooman",
        "traits": "Class flexibility",
        "lang": "Common",
        "link": ""
    },
    {
        "name":"Half-Orc",
        "height_ft": 6,
        "height_in": 0,
        "weight": 200,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Puny widdle normal hooman",
        "traits": "Class flexibility",
        "lang": "Common",
        "link": ""
    }
];
