var races = [
    {
        "name":"Human",
        "height_ft": 5,
        "height_in": 10,
        "weight": 170,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Humans are the most adaptable of the races, able to survive comfortably in many environments and situations. Because of this, their civilizations span across the world, diverse cultures sprawling across all the land. They are curious, ambitious, and adventurous, traits which match as well with a traveling bard as they do with a conquering emperor.",
        "traits": "Bonus Feat, Skilled",
        "lang": "Common",
        "link": "http://phaser.io/examples/v2/category/tilemaps"
    },
    {
        "name":"Elf",
        "height_ft": 6,
        "height_in": 5,
        "weight": 140,
        "mods": "+2 Dex | +2 Int | -2 Con",
        "spd": 30,
        "size": "Medium",
        "desc": "Elves are private creatures of beauty. Long-lived, close to nature, and with an affinity for magic, elves make for excellent rangers and classes to do with spellcasting. Though they are sometimes vain and conservative but they have some diversity among their race as well, sometimes taking on aspects of the environment where they live. Elves are tall, long, and lean, they have pointed ears and large eyes, and often flowing hair. They are slow to make friends but are extremely loyal.",
        "traits": "Low-Light Vision, Elven Immunities, Elven Magic, Keen Senses, Weapon Familiarity",
        "lang": "Common, Elvish",
        "link": ""
    },
    {
        "name":"Half-Elf",
        "height_ft": 6,
        "height_in": 1,
        "weight": 160,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Thanks to their beauty and ethereal auras, elves often draw the gaze of other races and have on occassion produced heirs with humans, creating half-elves. Half-elves benefit from both of their parent's traits, combining the adaptability and versatility of humans with the magical affinity and sensory advantages of elves. They don't have a solid culture or society, being caught between humans and elves, and as such have developed a certain freedom from societal bonds. Because of this, half-elves often lean towards a Chaotic Good alignment.",
        "traits": "Low-Light Vision, Adaptability, Elf Blood, Elven Immunities, Keen Senses, Multitalented",
        "lang": "Common, Elven",
        "link": ""
    },
    {
        "name":"Dwarf",
        "height_ft": 4,
        "height_in": 0,
        "weight": 240,
        "mods": "+2 Con | +2 Wis | -2 Cha",
        "spd": 20,
        "size": "Medium",
        "desc": "Dwarves are short, stocky, hairy, powerful beings known for their affinity for mining and craftsmanship. They're formidable fighters who prefer living in high mountain cities and deep caverns, carving their buildings from the rock itself. They mine for treasure and useful materials to use in their weapons and armor, which are widely regarded as some of the best in the world. Dwarves are steadfast, stubborn, and solid creatures who value solitude and hard work.",
        "traits": "Darkvision, Defensive Training, Greed, Hatred, Hardy, Stability, Stonecunning, Weapon Familiarity",
        "lang": "Common, Dwarven",
        "link": ""
    },
    {
        "name":"Gnome",
        "height_ft": 3,
        "height_in": 2,
        "weight": 90,
        "mods": "+2 Con | +2 Cha | +1 AC | +1 Atk | -2 Str | -1 CMB | -1 CMD | +4 to Stealth checks",
        "spd": 20,
        "size": "Small",
        "desc": "Gnomes have their roots in the land of the fey which make them strange and alien to other races. They are small beings with bright hair, earthy skin, and cartoonish feeatures. Gnomes are typically wanderers and don't typically live in groups, prefering travel and temporary companions to civilization and society. They are obsessive creatures who devote much of their time into their crafts and professions. They prefer action to strategy and instinct to technique, and make for excellent bards and sorcerers.",
        "traits": "Low-Light Vision, Defensive Training, Gnome Magic, Hatred, Illusion, Keen Senses, Obsessive, Weapon Familiarity",
        "lang": "Common, Gnome, Sylvan",
        "link": ""
    },
    {
        "name":"Halfling",
        "height_ft": 3,
        "height_in": 0,
        "weight": 80,
        "mods": "+2 Con | +2 Cha | +1 AC | +1 Atk | -2 Str | -1 CMB | -1 CMD | +4 to Stealth checks",
        "spd": 20,
        "size": "Small",
        "desc": "Halflings are small, cheerful, wild creatures. They have no real community, but they value home above all else, despite their powerful wanderlust. Halflings are also curious, clever, and lucky, able to hide amongst crowds easily and disappear out of sight. They are opportunists and strategists, unused to physical confrontation and prefering to use their stealth, wits, and wiles to accomplish their goals. They have slightly pointed ears and curly hair on both their heads and the tops of their larger-than-average feet. Halflings make for excellent rogues, although they can also easily fit the role of a bard or ranger.",
        "traits": "Fearless, Halfling Luck, Keen Senses, Sure-Footed, Weapon Familiarity",
        "lang": "Common, Halfling",
        "link": ""
    },
    {
        "name":"Half-Orc",
        "height_ft": 6,
        "height_in": 5,
        "weight": 200,
        "mods": "+2 to any Ability Score",
        "spd": 30,
        "size": "Medium",
        "desc": "Born of a meeting of human and orc, half-orcs are beings of strength and vigor. They're often met with prejudice and discrimination which leaves them quick to anger and slow to trust others, but are also revered for their natural skill with martial arts, strategy, and leadership. Half-orcs stand taller than humans and have powerful bodies with green or gray skin and small tusks protruding from their mouths. They may appear hard and intimidating from the surface but many half-orcs have an empathetic core and care deeply for their friends.",
        "traits": "Darkvision, Intimidating, Orc Blood, Orc Ferocity, Weapon Familiarity",
        "lang": "Common, Orc",
        "link": ""
    }
];
